site_name: MarkMate Documentation
site_description: Your AI Teaching Assistant for Assignments and Assessment
site_url: https://mark-mate.readthedocs.io
repo_url: https://github.com/markmate-ai/mark-mate
repo_name: markmate-ai/mark-mate

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - content.code.copy

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true
            show_category_heading: true

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quickstart.md
    - GUI vs CLI: getting-started/gui-vs-cli.md
  - Workflow:
    - Overview: workflow/overview.md
    - Consolidate: workflow/consolidate.md
    - Scan: workflow/scan.md
    - Extract: workflow/extract.md
    - Grade: workflow/grade.md
  - Configuration:
    - Grading Configuration: configuration/grading-config.md
    - System Settings: configuration/system-settings.md
    - Templates: configuration/templates.md
  - AI & Prompts:
    - Overview: ai-prompts/overview.md
    - Custom Prompts: ai-prompts/custom-prompts.md
    - LLM Providers: ai-prompts/llm-providers.md
  - Examples:
    - Programming: examples/programming.md
    - WordPress: examples/wordpress.md
    - International: examples/international.md
    - Custom Workflows: examples/custom-workflows.md
  - Technical:
    - Architecture: technical/architecture.md
    - GUI Design: technical/gui-design.md
    - CLI Reference: technical/cli-reference.md
    - API Documentation: technical/api.md
  - Advanced:
    - Extending MarkMate: advanced/extending.md
    - Custom Extractors: advanced/custom-extractors.md
    - Integration: advanced/integration.md
    - Troubleshooting: advanced/troubleshooting.md

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true

extra_javascript:
  - https://unpkg.com/mermaid@10.6.1/dist/mermaid.min.js