site_name: MarkMate Documentation
site_description: Your AI Teaching Assistant for Assignments and Assessment
site_url: https://mark-mate.readthedocs.io
repo_url: https://github.com/markmate-ai/mark-mate
repo_name: markmate-ai/mark-mate

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - content.code.copy

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true
            show_category_heading: true

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quickstart.md
  - User Guide:
    - Consolidation: user-guide/consolidation.md
    - Scanning: user-guide/scanning.md
    - Extraction: user-guide/extraction.md
    - Grading: user-guide/grading.md
    - Configuration: user-guide/configuration.md
  - API Reference:
    - Core: api/core.md
    - CLI: api/cli.md
    - Extractors: api/extractors.md
    - Analyzers: api/analyzers.md
  - Development:
    - Contributing: development/contributing.md
    - Testing: development/testing.md
    - Architecture: development/architecture.md

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true